"""
scripts/measure_overhead.py — MAJ-12 timing methodology.

Re-measures the per-component wall-clock cost of the four production
detectors plus the AIF prediction path with a documented protocol:

  * Clock              : ``time.perf_counter`` (monotonic, highest
                         platform resolution; the same clock that
                         ``timeit`` uses internally).
  * Warm-up exclusion  : ``WARMUP = 20`` calls per component, discarded
                         before any measurement is recorded.
  * Steady-state sample: ``MEASURE = 200`` calls per component
                         recorded individually (NOT averaged in the
                         hot path) so we can compute distributional
                         statistics.
  * Hardware footprint : captured via ``platform.processor()``,
                         ``platform.uname()``, ``os.cpu_count()``,
                         ``psutil`` (if available) — emitted as a
                         single ``hardware`` block in the JSON dump.
  * Confidence interval: percentile bootstrap 95% CI on the mean
                         (10 000 resamples) per component.

Why standalone?
~~~~~~~~~~~~~~~
The bar chart that ships with the thesis (``fig_computational_overhead.pdf``,
generated by ``thesis/generate_eval_figures.py::fig_overhead``) reports
``timeit.timeit(...) / N * 1000`` --- a single point estimate over
N=50 calls with no warm-up exclusion and no hardware footnote.  This
script adds the missing artefacts (warm-up discipline, per-call
distribution, CI, hardware) and dumps everything to
``thesis/.repro_audit_data/overhead_timings.json`` so the thesis can
quote concrete numbers traceable to a single audited measurement.

Outputs:
  * thesis/.repro_audit_data/overhead_timings.json
  * thesis/figures/fig_computational_overhead.pdf  (overwritten with
    error-bar version)
"""
from __future__ import annotations

import json
import os
import platform
import sys
import time
from pathlib import Path
from typing import Callable

import numpy as np
import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from sklearn.ensemble import RandomForestClassifier  # noqa: E402

from aif.aif import AIF  # noqa: E402
from aif.buffers import BufferPair  # noqa: E402
from detectors.cdd import CDD  # noqa: E402
from detectors.cpd import CPD  # noqa: E402
from detectors.ddd import DDD  # noqa: E402
from detectors.dpd import DPD  # noqa: E402

WARMUP = 20
MEASURE = 200
BOOTSTRAP_RESAMPLES = 10_000
SEED = 0

JSON_OUT = ROOT / "thesis" / ".repro_audit_data" / "overhead_timings.json"
FIG_OUT = ROOT / "thesis" / "figures" / "fig_computational_overhead.pdf"


def _hardware_block() -> dict:
    """Capture host hardware identity for the measurement footnote."""
    block: dict[str, object] = {
        "python_version": sys.version.split()[0],
        "platform": platform.platform(),
        "system": platform.system(),
        "release": platform.release(),
        "machine": platform.machine(),
        "processor": platform.processor() or "unknown",
        "os_cpu_count": os.cpu_count(),
        "numpy_version": np.__version__,
    }
    try:
        import sklearn

        block["sklearn_version"] = sklearn.__version__
    except Exception:
        block["sklearn_version"] = "unknown"
    try:
        import psutil

        block["physical_cores"] = psutil.cpu_count(logical=False)
        block["logical_cores"] = psutil.cpu_count(logical=True)
        vm = psutil.virtual_memory()
        block["total_memory_GiB"] = round(vm.total / (1024 ** 3), 2)
    except ImportError:
        block["physical_cores"] = None
        block["logical_cores"] = block["os_cpu_count"]
        block["total_memory_GiB"] = None
    block["clock"] = "time.perf_counter (monotonic, ns resolution)"
    block["clock_resolution_ns"] = time.get_clock_info("perf_counter").resolution * 1e9
    return block


def _bootstrap_ci(samples: np.ndarray, statistic: Callable[[np.ndarray], float],
                  n_resamples: int = BOOTSTRAP_RESAMPLES,
                  alpha: float = 0.05, seed: int = SEED) -> tuple[float, float]:
    rng = np.random.default_rng(seed)
    n = samples.size
    boots = np.empty(n_resamples, dtype=float)
    for k in range(n_resamples):
        idx = rng.integers(0, n, size=n)
        boots[k] = statistic(samples[idx])
    lo = float(np.percentile(boots, 100.0 * alpha / 2.0))
    hi = float(np.percentile(boots, 100.0 * (1.0 - alpha / 2.0)))
    return lo, hi


def _measure(label: str, call: Callable[[], None]) -> dict:
    """Time ``call`` for WARMUP + MEASURE iterations, return statistics."""
    # Warm-up — discarded
    for _ in range(WARMUP):
        call()
    samples_ms = np.empty(MEASURE, dtype=float)
    for i in range(MEASURE):
        t0 = time.perf_counter()
        call()
        samples_ms[i] = (time.perf_counter() - t0) * 1000.0
    mean_ms = float(samples_ms.mean())
    std_ms = float(samples_ms.std(ddof=1))
    p50 = float(np.percentile(samples_ms, 50))
    p95 = float(np.percentile(samples_ms, 95))
    p99 = float(np.percentile(samples_ms, 99))
    ci_lo, ci_hi = _bootstrap_ci(samples_ms, np.mean)
    return {
        "label": label,
        "n_warmup": WARMUP,
        "n_measure": MEASURE,
        "mean_ms": mean_ms,
        "std_ms": std_ms,
        "p50_ms": p50,
        "p95_ms": p95,
        "p99_ms": p99,
        "ci95_mean_lo_ms": ci_lo,
        "ci95_mean_hi_ms": ci_hi,
        "min_ms": float(samples_ms.min()),
        "max_ms": float(samples_ms.max()),
    }


def _build_components():
    rng = np.random.default_rng(SEED)
    X_ref = rng.normal(0, 1, (200, 4))
    X_rec = rng.normal(0, 1, (100, 4))
    y_ref = rng.integers(0, 2, 200).astype(int)
    p_ref = rng.integers(0, 2, 200).astype(float)
    p_rec = rng.integers(0, 2, 100).astype(float)

    ddd = DDD(reference_size=200, recent_size=100, ks_alpha=0.05)
    ddd.fit_reference(X_ref)
    dpd = DPD(reference_size=200, recent_size=50)
    dpd.fit_reference(X_ref)
    cdd = CDD(task="classifier", reference_window=150,
              recent_window=50, ph_lambda=40.0)
    for xi, yi, pi in zip(X_ref, y_ref, p_ref):
        cdd.update(y_pred=np.array([pi]), y_true=float(yi))
    cpd = CPD(task="classifier", reference_size=200,
              recent_size=100, shadow_threshold=0.38)
    cpd.fit_reference(X_ref, y_ref, p_ref)

    buf = BufferPair(maxlen=2000)
    buf.push_batch(X_ref, p_ref)
    buf.push_batch(X_rec, p_rec)

    clf = RandomForestClassifier(n_estimators=50, random_state=1).fit(X_ref, y_ref)
    aif = AIF(clf)
    return aif, ddd, dpd, cdd, cpd, buf, X_rec


def main() -> int:
    aif, ddd, dpd, cdd, cpd, buf, X_rec = _build_components()

    components = [
        ("AIF.predict", lambda: aif.predict(X_rec[0])),
        ("DDD.check",   lambda: ddd.check(buf.lib)),
        ("DPD.check",   lambda: dpd.check(buf.lib)),
        ("CDD.check",   lambda: cdd.check()),
        ("CPD.check",   lambda: cpd.check(buf.lib, buf.lob)),
    ]

    print(f"Measuring {len(components)} components "
          f"(warmup={WARMUP}, measure={MEASURE}, "
          f"bootstrap={BOOTSTRAP_RESAMPLES})...")
    rows = [_measure(label, call) for label, call in components]
    for r in rows:
        print(f"  {r['label']:<14}  mean={r['mean_ms']:6.3f} ms  "
              f"95% CI=[{r['ci95_mean_lo_ms']:.3f}, {r['ci95_mean_hi_ms']:.3f}]  "
              f"p50={r['p50_ms']:.3f}  p95={r['p95_ms']:.3f}")

    # Detector-only sum (excludes AIF.predict, which is the model
    # call that the engine pays once per sample, not once per check).
    detector_only_means = [r["mean_ms"] for r in rows
                           if r["label"].endswith(".check")]
    detector_total_mean = float(sum(detector_only_means))

    payload = {
        "metadata": {
            "warmup_calls": WARMUP,
            "measure_calls": MEASURE,
            "bootstrap_resamples": BOOTSTRAP_RESAMPLES,
            "seed": SEED,
            "alpha": 0.05,
        },
        "hardware": _hardware_block(),
        "components": rows,
        "detector_total_mean_ms": detector_total_mean,
    }
    JSON_OUT.parent.mkdir(parents=True, exist_ok=True)
    JSON_OUT.write_text(json.dumps(payload, indent=2), encoding="utf-8")
    print(f"\nWrote {JSON_OUT.relative_to(ROOT)}")
    print(f"  Detector-only total (sum of *.check means): "
          f"{detector_total_mean:.3f} ms")

    # ----------------------------------------------------------------------
    # Re-render fig_computational_overhead.pdf with 95% CI error bars
    # ----------------------------------------------------------------------
    names = [r["label"] for r in rows]
    means = np.array([r["mean_ms"] for r in rows])
    los = np.array([r["ci95_mean_lo_ms"] for r in rows])
    his = np.array([r["ci95_mean_hi_ms"] for r in rows])
    err_lo = means - los
    err_hi = his - means
    colours = ["#3498db", "#8e44ad", "#e67e22", "#27ae60", "#e74c3c"]

    fig, ax = plt.subplots(figsize=(8, 4.2))
    bars = ax.barh(names, means, color=colours,
                   edgecolor="white", height=0.55,
                   xerr=[err_lo, err_hi],
                   capsize=4,
                   error_kw={"elinewidth": 1.0, "ecolor": "#333333"})
    for bar, m, lo, hi in zip(bars, means, los, his):
        ax.text(hi + 0.04 * max(means),
                bar.get_y() + bar.get_height() / 2,
                f"{m:.2f} ms (95% CI [{lo:.2f}, {hi:.2f}])",
                va="center", fontsize=8.5)

    ax.axvline(detector_total_mean, color="#444444", ls="--", lw=1)
    ax.text(detector_total_mean + 0.01 * max(means),
            len(names) - 0.45,
            f"sum of detector means: {detector_total_mean:.2f} ms",
            fontsize=8.5, color="#444444")

    ax.set_xlabel("Mean per-call wall-clock latency (ms)")
    ax.set_title(
        f"Per-component latency (perf_counter, "
        f"warmup={WARMUP}, n={MEASURE} measurements, "
        f"95% CI from {BOOTSTRAP_RESAMPLES}-resample bootstrap)",
        fontsize=10,
    )
    ax.set_xlim(0, max(his) * 1.55)
    fig.tight_layout()
    fig.savefig(FIG_OUT, bbox_inches="tight")
    plt.close(fig)
    print(f"Wrote {FIG_OUT.relative_to(ROOT)} "
          f"({FIG_OUT.stat().st_size / 1024:.1f} KB)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
